automation:
  - alias: mrj_start_menu_alarm_telegram
    initial_state: 'on'
    trigger:
      - platform: event
        event_type: telegram_command
        event_data:
          command: !secret dss_triggers_menu_telegram_command_allarme
          # command: '/alarm'
    action:
      - service: notify.notifiche_telegram
        data_template:
          title: "🛡️ <strong>Stato Allarme</strong> 🛡️"
          message: "Il tuo allarme attualmente è <strong>{%- if is_state('alarm_control_panel.home_alarm', 'armed_home') -%}Armato HOME{%- elif is_state('alarm_control_panel.home_alarm', 'armed_away') -%}Armato AWAY{% else %}Disarmato{% endif %}</strong>"
          #target: !secret allowed_chat_ids      
          data:
            inline_keyboard:
              - "{{ '\U0001F4A1' }} Gestione Allarme:/mrj_manage_alarm"
              - "{{ '\U0001f6d1' }} Chiudi:/removekeyboard"

  - alias: mrj_manage_menu_alarm_telegram
    initial_state: 'on'
    trigger:
    - platform: event
      event_type: telegram_callback
      event_data:
          data: '/mrj_manage_alarm'
    action:
      - service: telegram_bot.edit_message
        data_template:
          message_id: "{{ trigger.event.data.message.message_id }}"
          chat_id: "{{ trigger.event.data.message.chat.id }}"
          title: "🛡️ <strong>Gestione Allarme</strong> 🛡️"
          message: "Controllo Allarme, premi per lo switch"
          inline_keyboard: 
            - "{{ '\U0001f3e0' }} Attiva HOME:/mrj_arm_home, {{ '\U0001f513' }} Attiva AWAY:/mrj_arm_away"
            - "{{ '\U0001f513' }} Disarma:/mrj_disarm_alarm"
            - "{{ '\U0001f6d1' }} Chiudi:/removekeyboard"
      # - service: shell_command.log
        # data_template:
          # text: >
           # "Check allarme"
           
  - alias: mrj_disable_menu_alarm_telegram
    initial_state: 'on'
    trigger:
    - platform: event
      event_type: telegram_callback
      event_data:
          data: '/mrj_disarm_alarm'
    action:
      - service: telegram_bot.edit_message
        data_template:
          message_id: "{{ trigger.event.data.message.message_id }}"
          chat_id: "{{ trigger.event.data.message.chat.id }}"
          title: "🛡️ <strong>Switch Allarme</strong> 🛡️"
          message: > 
            Allarme casa Passo da: <strong>{%- if is_state('alarm_control_panel.home_alarm', 'armed_home') -%}Armato HOME{%- elif is_state('alarm_control_panel.home_alarm', 'armed_away') -%}Armato AWAY{% else %}Disarmato{% endif %}</strong>
          inline_keyboard: [ ]
          #target: !secret allowed_chat_ids
      - service: alarm_control_panel.alarm_disarm
        data:
          entity_id: alarm_control_panel.home_alarm 
      - service: notify.notifiche_telegram
        data_template:
          message: "a: <strong>Disarmato</strong>"
          #target: !secret allowed_chat_ids      
      # - service: shell_command.log
        # data_template:
          # text: >
           # "Alarm disarm"

  - alias: mrj_arm_home_menu_alarm_telegram
    initial_state: 'on'
    trigger:
    - platform: event
      event_type: telegram_callback
      event_data:
          data: '/mrj_arm_home'
    action:
      - service: telegram_bot.edit_message
        data_template:
          message_id: "{{ trigger.event.data.message.message_id }}"
          chat_id: "{{ trigger.event.data.message.chat.id }}"
          title: "🛡️ <strong>Switch Allarme</strong> 🛡️"
          message: > 
            Allarme casa Passo da: <strong>{%- if is_state('alarm_control_panel.home_alarm', 'armed_home') -%}Armato HOME{%- elif is_state('alarm_control_panel.home_alarm', 'armed_away') -%}Armato AWAY{% else %}Disarmato{% endif %}</strong>
          inline_keyboard: [ ]
          #target: !secret allowed_chat_ids
      - service: alarm_control_panel.alarm_arm_home
        data:
          entity_id: alarm_control_panel.home_alarm 
      - service: notify.notifiche_telegram
        data_template:
          title: "🛡️ <strong>Stato Allarme</strong> 🛡️"
          message: "a: <strong>Armato HOME</strong>"
          #target: !secret allowed_chat_ids                   
      # - service: shell_command.log
        # data_template:
          # text: >
           # " Alarm arm home"

  - alias: mrj_arm_away_menu_alarm_telegram
    initial_state: 'on'
    trigger:
    - platform: event
      event_type: telegram_callback
      event_data:
          data: '/mrj_arm_away'
    action:
      - service: telegram_bot.edit_message
        data_template:
          message_id: "{{ trigger.event.data.message.message_id }}"
          chat_id: "{{ trigger.event.data.message.chat.id }}"
          title: "🛡️ <strong>Switch Allarme</strong> 🛡️"
          message: > 
            Allarme casa Passo da: <strong>{%- if is_state('alarm_control_panel.home_alarm', 'armed_home') -%}Armato HOME{%- elif is_state('alarm_control_panel.home_alarm', 'armed_away') -%}Armato AWAY{% else %}Disarmato{% endif %}</strong>
          inline_keyboard: [ ]
          #target: !secret allowed_chat_ids             
      - service: alarm_control_panel.alarm_arm_away
        data:
          entity_id: alarm_control_panel.home_alarm 
      - service: notify.notifiche_telegram
        data_template:
          message: "a: <strong>Armato AWAY</strong>"
          #target: !secret allowed_chat_ids                      
      # - service: shell_command.log
        # data_template:
          # text: >
           # " Alarm arm away"
           
