homeassistant: 
  customize:
    switch.sonoff_10009fc500:
      friendly_name: "Luce camera da Letto"
      device_class: light

# lovelace

# type: entities
# entities:
  # - entity: switch.sonoff_10009fc500
# title: Luci camera da Letto
# show_header_toggle: false
